# Generated by Django 3.0.7 on 2020-06-11 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0002_auto_20200610_2229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='content',
            new_name='thumbnail',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='price',
            field=models.IntegerField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wishlist',
            name='title',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wishlist',
            name='url',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
