# Generated by Django 3.0.7 on 2020-06-11 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0003_auto_20200611_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='price',
            field=models.CharField(max_length=500),
        ),
    ]
