# Generated by Django 3.0.7 on 2020-07-30 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0003_auto_20200723_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversations',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
