# Generated by Django 3.0.7 on 2020-07-30 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0004_conversations_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversations',
            name='read',
        ),
    ]
