# Generated by Django 3.0.7 on 2020-06-04 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0003_auto_20200604_1804'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='gender',
            new_name='Relationship',
        ),
    ]
