# Generated by Django 3.0.7 on 2020-06-04 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0004_auto_20200604_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Birthday',
            field=models.IntegerField(blank=True, max_length=8, null=True),
        ),
    ]
