# Generated by Django 3.0.7 on 2020-06-07 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0007_user_tagline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Birthday',
            new_name='birthday',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Location',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Relationship',
            new_name='relationship',
        ),
    ]
