# Generated by Django 3.0.7 on 2020-06-07 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0008_auto_20200607_2223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='birthday',
            new_name='age',
        ),
    ]
