# Generated by Django 3.0.7 on 2020-06-10 15:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow', '0002_auto_20200610_1516'),
        ('jwt_auth', '0009_auto_20200607_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(related_name='followers', through='follow.Contact', to=settings.AUTH_USER_MODEL),
        ),
    ]
