# Generated by Django 3.0.7 on 2020-07-29 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0011_auto_20200723_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.CharField(blank=True, default='https://bit.ly/30vhZFs', max_length=500),
        ),
    ]
