# Generated by Django 3.0.7 on 2020-06-07 23:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0003_auto_20200607_2307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='owner',
            new_name='comment_owner',
        ),
        migrations.AddField(
            model_name='comments',
            name='post_owner',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
