# Generated by Django 3.0.7 on 2020-06-08 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0004_ratings_avg_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='avg_rating',
            field=models.FloatField(blank=True),
        ),
    ]
