# Generated by Django 3.0.7 on 2020-06-08 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0006_auto_20200608_0208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratings',
            name='avg_rating',
        ),
    ]
