# Generated by Django 3.0.7 on 2020-06-08 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0007_remove_ratings_avg_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
