# Generated by Django 3.0.7 on 2020-06-11 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0008_auto_20200608_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
