# Generated by Django 3.0.7 on 2020-07-05 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0012_auto_20200705_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='feedback',
            field=models.CharField(blank=True, choices=[('Unattractive', 'Unattractive'), ('Rude Interaction', 'Rude Interaction'), ('Unpleasant Smell', 'Unpleasant Smell'), ('Impoverished Vibes', 'Impoverished Vibes'), ('Disciminatory', 'Disciminatory')], max_length=100),
        ),
    ]
