# Generated by Django 3.0.7 on 2020-06-11 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='title',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
