# Generated by Django 3.0.7 on 2020-06-11 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_forum_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='image',
            field=models.CharField(blank=True, default='https://i.imgur.com/ZNxb6AE.jpg', max_length=500),
        ),
    ]
