# Generated by Django 3.0.7 on 2020-06-11 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_forum_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
