# Generated by Django 3.0.7 on 2020-07-21 01:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0009_auto_20200721_0134'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ForumComents',
            new_name='ForumComments',
        ),
    ]
