# Generated by Django 3.0.7 on 2020-07-21 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_auto_20200721_0140'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumcomments',
            name='forum',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='forums_comments', to='forum.Forum'),
            preserve_default=False,
        ),
    ]
