# Generated by Django 3.0.7 on 2020-07-21 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_forumcomments_forum'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forumcomments',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterField(
            model_name='forumcomments',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
