# Generated by Django 3.0.7 on 2020-07-21 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0012_auto_20200721_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumcomments',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='forum.ForumComments'),
        ),
    ]
