# Generated by Django 3.0.7 on 2020-07-22 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0014_auto_20200721_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='content',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='forum',
            name='description',
            field=models.CharField(blank=True, max_length=5000),
        ),
    ]
