# Generated by Django 3.0.7 on 2020-10-08 20:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0018_forumfollow'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='followers',
            field=models.ManyToManyField(through='forum.ForumFollow', to=settings.AUTH_USER_MODEL),
        ),
    ]
