# Generated by Django 3.0.7 on 2020-10-09 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0019_forum_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumcomments',
            name='image',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
