# Generated by Django 3.0.7 on 2020-07-23 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0001_initial'),
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messaging',
            name='conversation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='conversations.Conversations'),
            preserve_default=False,
        ),
    ]
