# Generated by Django 3.1.2 on 2020-10-29 19:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostRatings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('updated_at', models.DateField(default=datetime.date.today)),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='posts.post')),
                ('post_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postsratings', to=settings.AUTH_USER_MODEL)),
                ('rating_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postsrated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
