# Generated by Django 3.0.7 on 2020-06-08 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
        ('postRatings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postratings',
            name='rating_giver',
        ),
        migrations.AddField(
            model_name='postratings',
            name='owner',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='postsrating', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postratings',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='posts.Post'),
        ),
    ]
