# Generated by Django 3.0.7 on 2020-06-08 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('postRatings', '0002_auto_20200608_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postratings',
            name='owner',
        ),
        migrations.AddField(
            model_name='postratings',
            name='post_owner',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='postsratings', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postratings',
            name='rating_owner',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='postsrated', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
