# Generated by Django 3.0.7 on 2020-06-08 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postRatings', '0003_auto_20200608_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postratings',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
