# Generated by Django 3.0.7 on 2020-07-16 02:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postRatings', '0004_auto_20200608_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postratings',
            name='created_at',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='postratings',
            name='updated_at',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
